### ISSUE TITLE
Send push receipts in response on feed post creation

### ISSUE THREAD

**Issue by galenriley** [Chattahooligans/hooligan-hymnal-app#71]
Not getting pushes again, and no way to troubleshoot why after push receipts were removed. Please put them back in

**Comment by galenriley** [comment]
Still not working. Here are logs from chattahooligan-dev

` 2020-02-29T15:26:04.546368+00:00 app[web.1]: CHECKING FOR PUSH
 2020-02-29T15:26:04.546436+00:00 app[web.1]: PUSH TRUE
 2020-02-29T15:26:04.546522+00:00 app[web.1]: sending push...
 2020-02-29T15:26:04.546649+00:00 app[web.1]: ABOUT TO RETURN
 2020-02-29T15:26:04.559233+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[NQjQBqBjcnAfQk8N-3R2al]
 2020-02-29T15:26:04.559309+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[HcDpdlINasiVlvc8fOIlEa]
 2020-02-29T15:26:04.559371+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[rA-sHTCBP85w2U3D9kix17]
 2020-02-29T15:26:04.559430+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[r76-uHJwwHZM8y5OwgXNOW]
 2020-02-29T15:26:04.559510+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[I8QML2Ir_01kPeOXEfjizU]
 2020-02-29T15:26:04.559567+00:00 app[web.1]: trying to send notification to token:  ExponentPushToken[jqoXnuCi8Acw2sk9Dtq_C2]
 2020-02-29T15:26:04.559624+00:00 app[web.1]: trying to push
 2020-02-29T15:26:04.560414+00:00 app[web.1]: [0mPOST /api/feed [32m200 [0m31.997 ms - 392[0m
 2020-02-29T15:26:04.709011+00:00 app[web.1]: there was a problem with the push
 2020-02-29T15:26:04.709157+00:00 app[web.1]: Error notifying with tokens [ExponentPushToken[NQjQBqBjcnAfQk8N-3R2al], ExponentPushToken[HcDpdlINasiVlvc8fOIlEa], ExponentPushToken[rA-sHTCBP85w2U3D9kix17], ExponentPushToken[r76-uHJwwHZM8y5OwgXNOW], ExponentPushToken[I8QML2Ir_01kPeOXEfjizU], ExponentPushToken[jqoXnuCi8Acw2sk9Dtq_C2]]: Error: All push notification messages in the same request must be for the same project; check the details field to investigate conflicting tokens.
 2020-02-29T15:26:04.710447+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
 2020-02-29T15:26:04.710447+00:00 app[web.1]:     at ServerResponse.setHeader (_http_outgoing.js:470:11)
 2020-02-29T15:26:04.710448+00:00 app[web.1]:     at ServerResponse.header (/app/node_modules/express/lib/response.js:771:10)
 2020-02-29T15:26:04.710449+00:00 app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:170:12)
 2020-02-29T15:26:04.710449+00:00 app[web.1]:     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
 2020-02-29T15:26:04.710449+00:00 app[web.1]:     at ServerResponse.send (/app/node_modules/express/lib/response.js:158:21)
 2020-02-29T15:26:04.710450+00:00 app[web.1]:     at PushTokens.find (/app/models/pushHandler.js:89:7)
 2020-02-29T15:26:04.710450+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:68:7)
 2020-02-29T15:26:04.710527+00:00 app[web.1]: (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
 2020-02-29T15:26:04.559831+00:00 heroku[router]: at=info method=POST path="/api/feed" host=chattahooligan-dev.herokuapp.com request_id=5a3305ba-0240-4c9c-8f43-819f7e849bc0 fwd="104.251.247.92" dyno=web.1 connect=0ms service=46ms status=200 bytes=826 protocol=https`

**Comment by galenriley** [comment]
expanding error.details on chattahooligan-dev yields

{"@chattahooligan/chattahooligan-hymnal":["ExponentPushToken[NQjQBqBjcnAfQk8N-3R2al]","ExponentPushToken[HcDpdlINasiVlvc8fOIlEa]","ExponentPushToken[I8QML2Ir_01kPeOXEfjizU]","ExponentPushToken[jqoXnuCi8Acw2sk9Dtq_C2]"],"@ngsdetroit/chattahooligan-hymnal":["ExponentPushToken[rA-sHTCBP85w2U3D9kix17]","ExponentPushToken[r76-uHJwwHZM8y5OwgXNOW]"]}

Good candidates for deletion. Maybe we store the acceptable expo experience in an environment variable and not accept registration of tokens that don't match, and purge them as well

**Comment by galenriley** [comment]
for some reason, response.data is valid inside feedService.createPost but not returning sucessfully. Shows as undefined after the function exits

**Comment by tacoman** [comment]
Deleting those would help for sure. Regarding your broken return issue: this may be why:

UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client 

Maybe multiple attempts to send data or set the error code are doing this. I'd look into that error to be sure, but I'd bet you it's the root.

**Comment by galenriley** [comment]
that error is triggered by

res.send({ errors: errors, receipts: receipts });

**Comment by galenriley** [comment]
feedController .store appears to return before pushHandler completes

maybe this should be in an ELSE block, if .push is not true?
return res.json(feedItem);

and/or maybe pushHandler doesn't need to be calling res.send() in the first place, but instead return something that's used in the calling block in the first place

logs:
2020-03-03T02:28:14.286748+00:00 app[web.1]: CHECKING FOR PUSH
2020-03-03T02:28:14.286931+00:00 app[web.1]: PUSH TRUE
2020-03-03T02:28:14.287669+00:00 app[web.1]: sending push...
**2020-03-03T02:28:14.288144+00:00 app[web.1]: ABOUT TO RETURN
2020-03-03T02:28:14.296528+00:00 app[web.1]: trying to send notification to token:**  ExponentPushToken[NQjQBqBjcnAfQk8N-3R2al]
...and so on

**Comment by galenriley** [comment]
i could misunderstand how Promises work, but something is def fishy with how the logs come out vs when the code is executed.

Maybe async/await for pushHandler will do the job?

**Comment by tacoman** [comment]
Honestly, it should be the latter, and res shouldn't be passed in- but I struggled to get async/await to work when I tried doing it, and obviously I failed to do it via promises as well. Collin or you might be able to fix it in short order.

**Comment by galenriley** [comment]
Lmk when you are able to code again. I don't have the capacity to learn how all of the server code works from scratch and also not be 2 months behind on starting Prideraiser. At least we have a hint on what's happening and how to fix it

**Comment by galenriley** [comment]
Latest error
`2020-03-10T16:38:15.695039+00:00 app[web.1]: There was an error sending a notification: {"id":"01daeac4-3a18-4336-857d-25e1d0b9a505","status":"error","message":"The recipient device is not registered with FCM.","details":{"error":"DeviceNotRegistered","fault":"developer"}}
2020-03-10T16:38:15.695163+00:00 app[web.1]: Receipt cleanup error:  TypeError: Cannot read property 'length' of null`

**Comment by galenriley** [comment]
This error comes from pushHandler.js line 141. It's probably referring to the regex check returning null instead of an empty array, but that's just a guess.

What's interesting is that these "device not registered with FCM" error types is that there's no pushtoken in the message that we can subsequently go delete. I'm not sure how to handle them?

Maybe the receipt ID can be used as a lookup (to what?) to determine the problem tokens

**Comment by galenriley** [comment]
Maybe we can make an array for every token in a particular chunk, look at every receipt (i think the valid tokens can be found in succesful receipts), and flag those that were good and delete everything else?

**Comment by tacoman** [comment]
@galenriley I'm getting pushes from Chattahooligan Hymnal and Guardbook both, can we close this out?

**Comment by galenriley** [comment]
The last I recall, the server is not returning a list of tokens. It should for debugging purposes. Recall that Chattahooligan Hymnal has a current issue with push notifications.
